const sampleData = [
    {
        clubName: 'Dramatics Club',
        clubLogo: './src/assets/LogoPlaceholder.svg',
        followed: true,
        recruiting: true,
        upcomingEvent: true,
        applicationDeadline: '04 JUN 2024',
        shortDescription: `One morning, when Gregor Samsa woke from troubled dreams, he found himself transformed in his bed into a horrible vermin. He lay on his armour-like back, and if he lifted his head a little he could see his brown belly, slightly domed and divided by arches into stiff sections. The bedding was hardly able to cover it and seemed ready to slide off any moment. His many legs, pitifully thin compared with the size of the rest of him, waved about helplessly as he looked. "What's happened to me?" he thought. It wasn't a dream. His room, a proper human room although a little too small, lay peacefully between its four familiar walls. A collection of textile samples lay spread`,
        eventTitle: 'Some Event Title',
        eventDescription: `But I must explain to you how all this mistaken idea of denouncing pleasure and praising pain was born and I will give you a complete account of the system, and expound the actual teachings of the great explorer of the truth, the master-builder of human happiness. No one rejects, dislikes, or avoids pleasure itself, because it is pleasure, but because those who do not know how to pursue pleasure rationally encounter consequences that are extremely painful.`,
        eventDay: `TUE`,
        eventDate: `4`,
        eventMonth: `JUNE`,
        eventTime: `3:00 pm - 5:00 pm`,
    },
    {
        clubName: 'Dance Club',
        clubLogo: './src/assets/LogoPlaceholder.svg',
        followed: true,
        recruiting: true,
        upcomingEvent: false,
        applicationDeadline: '04 JUN 2024',
        shortDescription: `One morning, when Gregor Samsa woke from troubled dreams, he found himself transformed in his bed into a horrible vermin. He lay on his armour-like back, and if he lifted his head a little he could see his brown belly, slightly domed and divided by arches into stiff sections. The bedding was hardly able to cover it and seemed ready to slide off any moment. His many legs, pitifully thin compared with the size of the rest of him, waved about helplessly as he looked. "What's happened to me?" he thought. It wasn't a dream. His room, a proper human room although a little too small, lay peacefully between its four familiar walls. A collection of textile samples lay spread`,
        eventTitle: 'Some Event Title',
        eventDescription: `But I must explain to you how all this mistaken idea of denouncing pleasure and praising pain was born and I will give you a complete account of the system, and expound the actual teachings of the great explorer of the truth, the master-builder of human happiness. No one rejects, dislikes, or avoids pleasure itself, because it is pleasure, but because those who do not know how to pursue pleasure rationally encounter consequences that are extremely painful. Nor again is there anyone who loves or pursues or desires to obtain pain of itself, because it is pain, but because occasionally circumstances occur in which toil and pain can procure him some great pleasure`,
        eventDay: `MON`,
        eventDate: `10`,
        eventMonth: `JUNE`,
        eventTime: `3:00 pm - 5:00 pm`,
    },
    {
        clubName: 'Literature and Debate Club',
        clubLogo: './src/assets/LogoPlaceholder.svg',
        followed: true,
        recruiting: false,
        upcomingEvent: true,
        applicationDeadline: '04 JUN 2024',
        shortDescription: `One morning, when Gregor Samsa woke from troubled dreams, he found himself transformed in his bed into a horrible vermin. He lay on his armour-like back, and if he lifted his head a little he could see his brown belly, slightly domed and divided by arches into stiff sections. The bedding was hardly able to cover it and seemed ready to slide off any moment. His many legs, pitifully thin compared with the size of the rest of him, waved about helplessly as he looked. "What's happened to me?" he thought. It wasn't a dream. His room, a proper human room although a little too small, lay peacefully between its four familiar walls. A collection of textile samples lay spread`,
        eventTitle: 'Some Event Title',
        eventDescription: `But I must explain to you how all this mistaken idea of denouncing pleasure and praising pain was born and I will give you a complete account of the system, and expound the actual teachings of the great explorer of the truth, the master-builder of human happiness. No one rejects, dislikes, or avoids pleasure itself, because it is pleasure, but because those who do not know how to pursue pleasure rationally encounter consequences that are extremely painful. Nor again is there anyone who loves or pursues or desires to obtain pain of itself, because it is pain, but because occasionally circumstances occur in which toil and pain can procure him some great pleasure`,
        eventDay: `MON`,
        eventDate: `10`,
        eventMonth: `JUNE`,
        eventTime: `3:00 pm - 5:00 pm`,
    },
    {
        clubName: 'Debate Club',
        clubLogo: './src/assets/LogoPlaceholder.svg',
        followed: false,
        recruiting: true,
        upcomingEvent: false,
        applicationDeadline: '04 JUN 2024',
        shortDescription: `One morning, when Gregor Samsa woke from troubled dreams, he found himself transformed in his bed into a horrible vermin. He lay on his armour-like back, and if he lifted his head a little he could see his brown belly, slightly domed and divided by arches into stiff sections. The bedding was hardly able to cover it and seemed ready to slide off any moment. His many legs, pitifully thin compared with the size of the rest of him, waved about helplessly as he looked. "What's happened to me?" he thought. It wasn't a dream. His room, a proper human room although a little too small, lay peacefully between its four familiar walls. A collection of textile samples lay spread`,
        eventTitle: 'Some Event Title',
        eventDescription: `But I must explain to you how all this mistaken idea of denouncing pleasure and praising pain was born and I will give you a complete account of the system, and expound the actual teachings of the great explorer of the truth, the master-builder of human happiness. No one rejects, dislikes, or avoids pleasure itself, because it is pleasure, but because those who do not know how to pursue pleasure rationally encounter consequences that are extremely painful. Nor again is there anyone who loves or pursues or desires to obtain pain of itself, because it is pain, but because occasionally circumstances occur in which toil and pain can procure him some great pleasure`,
        eventDay: `MON`,
        eventDate: `10`,
        eventMonth: `JUNE`,
        eventTime: `3:00 pm - 5:00 pm`,
    },
    {
        clubName: 'Quiz Club',
        clubLogo: './src/assets/LogoPlaceholder.svg',
        followed: false,
        recruiting: false,
        upcomingEvent: true,
        applicationDeadline: '04 JUN 2024',
        shortDescription: `One morning, when Gregor Samsa woke from troubled dreams, he found himself transformed in his bed into a horrible vermin. He lay on his armour-like back, and if he lifted his head a little he could see his brown belly, slightly domed and divided by arches into stiff sections. The bedding was hardly able to cover it and seemed ready to slide off any moment. His many legs, pitifully thin compared with the size of the rest of him, waved about helplessly as he looked. "What's happened to me?" he thought. It wasn't a dream. His room, a proper human room although a little too small, lay peacefully between its four familiar walls. A collection of textile samples lay spread`,
        eventTitle: 'Some Event Title',
        eventDescription: `But I must explain to you how all this mistaken idea of denouncing pleasure and praising pain was born and I will give you a complete account of the system, and expound the actual teachings of the great explorer of the truth, the master-builder of human happiness. No one rejects, dislikes, or avoids pleasure itself, because it is pleasure, but because those who do not know how to pursue pleasure rationally encounter consequences that are extremely painful. Nor again is there anyone who loves or pursues or desires to obtain pain of itself, because it is pain, but because occasionally circumstances occur in which toil and pain can procure him some great pleasure`,
        eventDay: `MON`,
        eventDate: `10`,
        eventMonth: `JULY`,
        eventTime: `3:00 pm - 5:00 pm`,
    },
]

export default sampleData;